[daml]
disabled = true

[java]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[scala]
disabled = true

[gcloud]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
# truncation_length = 3
